apiVersion: v1
kind: Pod
metadata:
  labels:
    app: second
  name: busy-box-second
  namespace: alc-prod
spec:
  containers:
  - image: busybox
    name: busy-box-second
    command: ["sleep", "1324"]
