apiVersion: v1
kind: Pod
metadata:
  labels:
    run: persistentstorage
  name: persistentstorage
spec:
  containers:
  - image: nginx
    name: persistentstorage
    volumeMounts:
    - mountPath: /var/www/html
      name: myweb-volume
  volumes:
  - name: myweb-volume
    persistentVolumeClaim:
      claimName: my-claim 
