apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  volumes:
  - name: myvol
    emptyDir: {}
  containers:
  - name: runbusybox
    image: busybox
    command: ["/bin/sh", "-c", "if [ -f /busybox/run.txt ]; then sleep 1000; else exit 1; fi"]
    volumeMounts:
    - name: myvol
      mountPath: /busybox
  initContainers:
  - name: initbusybox
    image: busybox
    command: ["/bin/sh", "-c", "touch /busybox/run.txt;"]
    volumeMounts:
    - name: myvol
      mountPath: /busybox

