apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  volumes:
  - name: myvol01
    emptyDir: {}
  containers:
  - name: runalpine
    image: alpine
    command: ["/bin/sh", "-c", "if [ -f /alpine/runme.txt ]; then sleep 1000; else exit 1; fi"]
    volumeMounts:
    - name: myvol01
      mountPath: /alpine
  initContainers:
  - name: initalpine
    image: alpine
    command: ["/bin/sh", "-c", "touch /alpine/runme.txt;"]
    volumeMounts:
    - name: myvol01
      mountPath: /alpine   
