apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myalpine
  name: runme-pod
spec:
  containers:
  - image: alpine
    name: runme-pod
    command: [ "sleep", "1000"]
  - image: busybox
    name: mybusybox
    command: [ "sleep", "1000"]
