apiVersion: v1
kind: Pod
metadata:
  name: hungry-bear
spec: 
  volumes:
    - name: workdir
      emptyDir:
  containers:
  - name: checker
    image: alpine
    command: ["/bin/sh", "-c", "if [ -f /workdir/calm.txt ];
	      then sleep 100000; else exit 1; fi"]
    volumeMounts:
    - name: workdir
      mountPath: /workdir
#  initContainers:
#  - name: create
#    image: alpine
#    command: ["/bin/sh", "-c", "touch /workdir/calm.txt"]
#    volumeMounts:
#    - name: workdir
#      mountPath: /workdir 
